module Constant::FbDataNode
	Location = "Location"
	FbNullProperty = "<<not-applicable>>"
	FbDataNodeToLabel = {
		"city" => "City",
		"country" => "Country",
		"street" => "Street",
		"hometown" => "City",
		"state"		=> "State",
		"current_location" => Location,
		"founded" => "Time",
		"release_date" => "Time"
	}
	FbDataNodeToParentLabel = {
		"city" => "Location",
		"country" => "Location",
		"street" => "Location",
		"hometown" => "",
		"state"		=> "",
		"current_location" => "",
		"founded" => "Time",
		"release_date" => "Time"
	}

	FbNlpDescriptionPropertiesPrimary = [ "description", "about", "mission","bio", "company_overview", "general_info"]
	FbNlpDescriptionPropertiesSecondary = ["name"]
	FbDirectCommunitySearchProperties = ["written_by","starring","directed_by"] # comma separated
	FbDefaultCommunities = ["category", "category_list/","genre"] #slash in genre handled.
	FbDefaultCommunityRelevance = 0.987654321
	FbDataTimeHandleSpecially = ["birthday","founded","release_date"]

	FbAbstractCategory = ["Local Business or Place", "Company, Organization or Institution","Artist, Band or Public Figure", "Entertainment"]
	FbCategoryLocalBusinessOrPlace = ["Airport",
		"Arts/Entertainment/Nightlife",
		"Attractions/Things to Do",
		"Automotive",
		"Bank/Financial Services",
		"Bar",
		"Book Store",
		"Business Services",
		"Church/Religious Organization",
		"Club",
		"Community/Government",
		"Concert Venue",
		"Doctor",
		"Education",
		"Event Planning/Event Services",
		"Food/Grocery",
		"Health/Medical/Pharmacy",
		"Home Improvement",
		"Hospital/Clinic",
		"Hotel",
		"Landmark",
		"Lawyer",
		"Library",
		"Local Business",
		"Middle School",
		"Movie Theater",
		"Museum/Art Gallery",
		"Outdoor Gear/Sporting Goods",
		"Pet Services",
		"Professional Services",
		"Public Places",
		"Real Estate",
		"Restaurant/Cafe",
		"School",
		"Shopping/Retail",
		"Spas/Beauty/Personal Care",
		"Sports Venue",
		"Sports/Recreation/Activities",
		"Tours/Sightseeing",
		"Transportation",
		"University"]
	FbCategoryCompanyOrganizationOrInstitution = [
		"Aerospace/Defense",
		"Automobiles and Parts",
		"Bank/Financial Institution",
		"Biotechnology",
		"Cause",
		"Chemicals",
		"Church/Religious Organization",
		"Community Organization",
		"Company",
		"Computers/Technology",
		"Consulting/Business Services",
		"Education",
		"Elementary School",
		"Energy/Utility",
		"Engineering/Construction",
		"Farming/Agriculture",
		"Food/Beverages",
		"Government Organization",
		"Health/Beauty",
		"Health/Medical/Pharmaceuticals",
		"Industrials",
		"Insurance Company",
		"Internet/Software",
		"Legal/Law",
		"Media/News/Publishing",
		"Middle School",
		"Mining/Materials",
		"Non-Governmental Organization (NGO)",
		"Non-Profit Organization",
		"Organization",
		"Political Organization",
		"Political Party",
		"Preschool",
		"Retail and Consumer Merchandise",
		"School",
		"Small Business",
		"Telecommunication",
		"Transport/Freight",
		"Travel/Leisure",
		"University"]
	FbCategoryBrandOrProduct = ["App Page",
		"Appliances",
		"Baby Goods/Kids Goods",
		"Bags/Luggage",
		"Board Game",
		"Building Materials",
		"Camera/Photo",
		"Cars",
		"Clothing",
		"Commercial Equipment",
		"Computers",
		"Drugs",
		"Electronics",
		"Food/Beverages",
		"Furniture",
		"Games/Toys",
		"Health/Beauty",
		"Home Decor",
		"Household Supplies",
		"Jewelry/Watches",
		"Kitchen/Cooking",
		"Office Supplies",
		"Outdoor Gear/Sporting Goods",
		"Patio/Garden",
		"Pet Supplies",
		"Phone/Tablet",
		"Product/Service",
		"Software",
		"Tools/Equipment",
		"Video Game",
		"Vitamins/Supplements",
		"Website",
		"Wine/Spirits"]
	FbCategoryArtistBrandOrPublicFigure = ["Actor/Director",
		"Artist",
		"Athlete",
		"Author",
		"Blogger",
		"Business Person",
		"Chef",
		"Coach",
		"Comedian",
		"Dancer",
		"Designer",
		"Entertainer",
		"Entrepreneur",
		"Fictional Character",
		"Government Official",
		"Journalist",
		"Movie Character",
		"Musician/Band",
		"News Personality",
		"Pet",
		"Photographer",
		"Politician",
		"Producer",
		"Public Figure",
		"Teacher",
		"Writer"]
	FbCategoryEntertainment = ["Album",
		"Amateur Sports Team",
		"Book",
		"Book Series",
		"Book Store",
		"Concert Tour",
		"Concert Venue",
		"Fictional Character",
		"Library",
		"Magazine",
		"Movie",
		"Movie Character",
		"Movie Theater",
		"Music Award",
		"Music Chart",
		"Music Video",
		"Performance Art",
		"Radio Station",
		"Record Label",
		"School Sports Team",
		"Song",
		"Sports League",
		"Sports Team",
		"Sports Venue",
		"Studio",
		"TV Channel",
		"TV Network",
		"TV Show",
		"TV/Movie Award"]
 end